/**
 * Response Tags Constants
 * Used for identifying response types on client-side
 * Tags help in programmatic error handling and response identification
 */

const RESPONSE_TAGS = {
  // Success Tags
  SUCCESS: {
    OPERATION_SUCCESS: 'OPERATION_SUCCESS',
    USER_CREATED: 'USER_CREATED',
    USER_UPDATED: 'USER_UPDATED',
    USER_DELETED: 'USER_DELETED',
    USER_FOUND: 'USER_FOUND',
    USERS_FOUND: 'USERS_FOUND',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    TOKEN_REFRESHED: 'TOKEN_REFRESHED',
    FILE_UPLOADED: 'FILE_UPLOADED',
    DATA_RETRIEVED: 'DATA_RETRIEVED',
    DATA_CREATED: 'DATA_CREATED',
    DATA_UPDATED: 'DATA_UPDATED',
    DATA_DELETED: 'DATA_DELETED',
    HEALTH_CHECK: 'HEALTH_CHECK',
  },

  // Authentication & Authorization Error Tags
  AUTH: {
    UNAUTHORIZED: 'UNAUTHORIZED',
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    SESSION_EXPIRED: 'SESSION_EXPIRED',
    TOKEN_EXPIRED: 'TOKEN_EXPIRED',
    TOKEN_INVALID: 'TOKEN_INVALID',
    TOKEN_MISSING: 'TOKEN_MISSING',
    REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',
    REFRESH_TOKEN_EXPIRED: 'REFRESH_TOKEN_EXPIRED',
    INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
    FORBIDDEN: 'FORBIDDEN',
  },

  // Validation Error Tags
  VALIDATION: {
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    INVALID_INPUT: 'INVALID_INPUT',
    INVALID_EMAIL: 'INVALID_EMAIL',
    INVALID_PASSWORD: 'INVALID_PASSWORD',
    INVALID_ROLE: 'INVALID_ROLE',
    INVALID_FORMAT: 'INVALID_FORMAT',
    MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',
    INVALID_PARAMETER: 'INVALID_PARAMETER',
  },

  // Resource Error Tags
  RESOURCE: {
    NOT_FOUND: 'RESOURCE_NOT_FOUND',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    ALREADY_EXISTS: 'RESOURCE_ALREADY_EXISTS',
    USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
    DUPLICATE_ENTRY: 'DUPLICATE_ENTRY',
    CONFLICT: 'RESOURCE_CONFLICT',
  },

  // File Upload Error Tags
  FILE: {
    FILE_TOO_LARGE: 'FILE_TOO_LARGE',
    INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
    FILE_UPLOAD_FAILED: 'FILE_UPLOAD_FAILED',
    FILE_NOT_FOUND: 'FILE_NOT_FOUND',
    UNEXPECTED_FILE_FIELD: 'UNEXPECTED_FILE_FIELD',
  },

  // Database Error Tags
  DATABASE: {
    DATABASE_ERROR: 'DATABASE_ERROR',
    CONNECTION_ERROR: 'DATABASE_CONNECTION_ERROR',
    QUERY_ERROR: 'DATABASE_QUERY_ERROR',
    TRANSACTION_ERROR: 'DATABASE_TRANSACTION_ERROR',
  },

  // Server Error Tags
  SERVER: {
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
    GATEWAY_TIMEOUT: 'GATEWAY_TIMEOUT',
    MAINTENANCE_MODE: 'MAINTENANCE_MODE',
  },

  // Rate Limiting Tags
  RATE_LIMIT: {
    RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
    TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  },

  // Request Error Tags
  REQUEST: {
    BAD_REQUEST: 'BAD_REQUEST',
    INVALID_REQUEST: 'INVALID_REQUEST',
    ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',
    METHOD_NOT_ALLOWED: 'METHOD_NOT_ALLOWED',
    UNSUPPORTED_MEDIA_TYPE: 'UNSUPPORTED_MEDIA_TYPE',
  },

  // Business Logic Error Tags
  BUSINESS: {
    OPERATION_FAILED: 'OPERATION_FAILED',
    BUSINESS_RULE_VIOLATION: 'BUSINESS_RULE_VIOLATION',
    PRECONDITION_FAILED: 'PRECONDITION_FAILED',
    DEPENDENCY_ERROR: 'DEPENDENCY_ERROR',
  },
};

module.exports = RESPONSE_TAGS;

